name: Remove_Leavers_From_Identity_Protection_Watchist
description: Get leavers data from workday and remove from Identity protection watchlist after 30 day of their departure
provision_on_install: true
trigger:
    next:
        - workday_generate_access_token_115f40e2
    event: Schedule
    schedule:
        time_cycle: 0 5 */1 * *
        start_date: ""
        end_date: ""
        tz: Etc/UTC
        skip_concurrent: false
actions:
    workday_generate_access_token_115f40e2:
        next:
            - workday_get_leavers_data_db9dfb1f
        id: api_integrations.Workday_Generate_Access_Token.Generate_Access_Token
        properties:
            x-www-form-urlencoded:
                grant_type: refresh_token
                refresh_token: 132vq2l3636k29d6v6qhigw9m33qayk07smx76cpjy2fzavb1gcsh3svxvydk594hjtjqw9gnsa848p39v29a4j9jy5vbiy6w2sm
    workday_get_leavers_data_db9dfb1f:
        next:
            - activity_db9dfb1f_3216_4f68_8681_53e97c8e26f6_api_integration_custom_workday_get_leavers_workday_get_leavers_data_body_data_4c1773a1
        id: api_integrations.Workday_Get_Leavers.Get_Leavers
        properties:
            params:
                header:
                    authorization: ${workday_generate_access_token_115f40e2.API_Integration.Custom_Workday_Generate_Access_Token.Workday_Generate_Access_Token.body.token_type} ${workday_generate_access_token_115f40e2.API_Integration.Custom_Workday_Generate_Access_Token.Workday_Generate_Access_Token.body.access_token}
                query:
                    query: SELECT hireDate, preferredName as employee_name, email_PrimaryWork as employee_email, employeeID, lastDayOfWork, worker, terminationDate1 FROM allActiveAndTerminatedWorkers WHERE lastDayOfWork = '${cs.timestamp.format(cs.timestamp.now() - duration('720h'), '2006-01-02')}'
loops:
    ? activity_db9dfb1f_3216_4f68_8681_53e97c8e26f6_api_integration_custom_workday_get_leavers_workday_get_leavers_data_body_data_4c1773a1
    :   display: For each Data; Concurrently
        for:
            input: workday_get_leavers_data_db9dfb1f.API_Integration.Custom_Workday_Get_Leavers.Workday_Get_Leavers_Data.body.data
            continue_on_partial_execution: false
            sequential: false
        trigger:
            next:
                - get_user_identity_context_42e5157c
        actions:
            get_user_identity_context_42e5157c:
                next:
                    - user_ad_email_exists_9652626f
                id: 19c7e2af0a24f468be7797fe180c8329
                properties:
                    continue_if_entity_not_found: false
                    email: ${workday_get_leavers_data_db9dfb1f.API_Integration.Custom_Workday_Get_Leavers.Workday_Get_Leavers_Data.body.data.#.employee_email}
            remove_user_from_watchlist_264796c5:
                id: 844dcff30c42cba24e501be8a6cf2577
                properties:
                    user_id: ${get_user_identity_context_42e5157c.Enrich.User.EntitySid}
            write_to_log_repo_ab3a8b96:
                id: 0ec68880256f6192b9abef766d31fb04
                properties:
                    custom_json:
                        employeeEmail: ${get_user_identity_context_42e5157c.Enrich.User.Email}
                        employeeGUID: ${get_user_identity_context_42e5157c.Enrich.User.EntityGUID}
                        employeeName: ${get_user_identity_context_42e5157c.Enrich.User.EntityName}
                        error: Not removing from watchlist as employee account is 'cloud_only'
                    foundry_app_id: dc3b5a74533d409d9a2018e2325d4e9c
            write_to_log_repo_fba9f8a0:
                id: 0ec68880256f6192b9abef766d31fb04
                properties:
                    custom_json:
                        employeeEmail: ${workday_get_leavers_data_db9dfb1f.API_Integration.Custom_Workday_Get_Leavers.Workday_Get_Leavers_Data.body.data.#.employee_email}
                        employeeID: ${workday_get_leavers_data_db9dfb1f.API_Integration.Custom_Workday_Get_Leavers.Workday_Get_Leavers_Data.body.data.#.employeeID}
                        employeeName: ${workday_get_leavers_data_db9dfb1f.API_Integration.Custom_Workday_Get_Leavers.Workday_Get_Leavers_Data.body.data.#.employee_name.descriptor}
                        error: Employee with emaiId '${workday_get_leavers_data_db9dfb1f.API_Integration.Custom_Workday_Get_Leavers.Workday_Get_Leavers_Data.body.data.#.employee_email}' not exists in Identity Protection
                    foundry_app_id: dc3b5a74533d409d9a2018e2325d4e9c
        conditions:
            user_ad_email_exists_9652626f:
                next:
                    - user_object_sid_exists_user_entra_object_id_exists_a2b04cc6
                expression: get_user_identity_context_42e5157c.Enrich.User.Email:!null
                display:
                    - User AD email exists
                else:
                    - write_to_log_repo_fba9f8a0
            user_object_sid_exists_user_entra_object_id_exists_a2b04cc6:
                next:
                    - remove_user_from_watchlist_264796c5
                expression: get_user_identity_context_42e5157c.Enrich.User.EntitySid:!null+get_user_identity_context_42e5157c.Enrich.User.UserEntraObjectID:!null
                display:
                    - User object SID exists
                    - User Entra Object ID exists
                else:
                    - write_to_log_repo_ab3a8b96
